---

- name: common | Install pre dependency
  apt:
     pkg="{{ item }}"
     state=present
  with_items:
     - python-pip
     - libcurl3-gnutls
     - update-notifier-common

- name: common | Add zabbix.com repository key
  apt_key:
     url=http://repo.zabbix.com/zabbix-official-repo.key
     state=present
  register: zabbix_server_apt_key

- name: common | Add zabbix.com repository
  apt_repository:
     repo='deb http://repo.zabbix.com/zabbix/{{zabbix_server_major}}.{{zabbix_server_minor}}/{{ansible_distribution|lower}} {{ansible_lsb.codename}} main'
     state=present
  register: zabbix_server_apt_repo

- name : common | Update apt after adding repository
  apt :
     update_cache="yes"
  when: zabbix_server_apt_key | changed or zabbix_server_apt_repo | changed

- name: zabbix_server | Install Zabbix agent
  apt:
     pkg=zabbix-agent
     state=present
     force=yes

- name: zabbix_agent | Deploy zabbix_agentd.conf file
  template:
     src="agent/zabbix_agentd.conf.j2"
     dest="/etc/zabbix/zabbix_agentd.conf"
     owner=root
     group=root
     mode=0644
  notify: restart zabbix_agent
